[2020-01-17 14:56:13,429] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: GetAttachments.hello_task 2020-01-16T12:00:00+00:00 [queued]>
[2020-01-17 14:56:13,440] {{taskinstance.py:655}} INFO - Dependencies all met for <TaskInstance: GetAttachments.hello_task 2020-01-16T12:00:00+00:00 [queued]>
[2020-01-17 14:56:13,441] {{taskinstance.py:866}} INFO - 
--------------------------------------------------------------------------------
[2020-01-17 14:56:13,441] {{taskinstance.py:867}} INFO - Starting attempt 1 of 1
[2020-01-17 14:56:13,441] {{taskinstance.py:868}} INFO - 
--------------------------------------------------------------------------------
[2020-01-17 14:56:13,466] {{taskinstance.py:887}} INFO - Executing <Task(PythonOperator): hello_task> on 2020-01-16T12:00:00+00:00
[2020-01-17 14:56:13,472] {{standard_task_runner.py:52}} INFO - Started process 27567 to run task
[2020-01-17 14:56:13,532] {{logging_mixin.py:112}} INFO - [2020-01-17 14:56:13,532] {{dagbag.py:403}} INFO - Filling up the DagBag from /usr/local/airflow/dags/email.py
[2020-01-17 14:56:13,550] {{logging_mixin.py:112}} INFO - Running %s on host %s <TaskInstance: GetAttachments.hello_task 2020-01-16T12:00:00+00:00 [running]> 7f68746faaa4
[2020-01-17 14:56:13,564] {{python_operator.py:105}} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=GetAttachments
AIRFLOW_CTX_TASK_ID=hello_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-16T12:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-16T12:00:00+00:00
[2020-01-17 14:56:13,566] {{logging_mixin.py:112}} WARNING - usage: airflow [--auth_host_name AUTH_HOST_NAME] [--noauth_local_webserver]
               [--auth_host_port [AUTH_HOST_PORT [AUTH_HOST_PORT ...]]]
               [--logging_level {DEBUG,INFO,WARNING,ERROR,CRITICAL}]
[2020-01-17 14:56:13,567] {{logging_mixin.py:112}} WARNING - airflow: error: unrecognized arguments: run GetAttachments hello_task 2020-01-16T12:00:00+00:00 --local --pool default_pool -sd /usr/local/airflow/dags/email.py
[2020-01-17 14:56:23,403] {{logging_mixin.py:112}} INFO - [2020-01-17 14:56:23,403] {{local_task_job.py:103}} INFO - Task exited with return code 0
